name: Increment Version

inputs:
  git-user-email:
    description: 'Git User Email'
    required: true
  git-user-name:
    description: 'Git User Name'
    required: true
  mode:
    description: 'Version Level to Increment'
    required: false
    default: 'patch'
  preid:
    description: 'Pre-Release id'
    required: false
    default: 'beta'
  branch:
    description: 'Branch Name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "${{ inputs.git-user-email }}"
        git config --global user.name "${{ inputs.git-user-name }}"
      shell: bash
    - name: Increment prerelease Version
      if: "contains(inputs.mode, 'prerelease')"
      run: |
        npm --no-git-tag-version version prerelease --preid=beta
        CURRENT_VERSION=$(node -pe "require('./package.json').version")
        git commit -a -m $"Build ${CURRENT_VERSION}"
      shell: bash
    - name: Increment ${{ inputs.mode }} Version
      if: "!contains(inputs.mode, 'prerelease')"
      run: |
        npm version ${{ inputs.mode }}
      shell: bash
    - name: Push Version
      run: |
        echo ${{ inputs.branch }}
        git push --set-upstream origin ${{ inputs.branch }} --tags
      shell: bash
