name: Run Tests

inputs:
  nodeVersion:
    description: 'Node Version'
    required: false
    default: '16.x'
  githubToken:
    description: 'GitHub Token'
    required: false
    default: '${{ github.token }}'  

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ inputs.nodeVersion }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@bigblueswimschool'
        cache: 'yarn'
    - run: |
        yarn
        yarn test
      env:
        NODE_AUTH_TOKEN: ${{ inputs.githubToken }}
      shell: bash
