name: Run Tests

inputs:
  nodeVersion:
    description: 'Node Version'
    required: false
    default: '24.x'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ inputs.nodeVersion }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'yarn'
    - name: Authenticate with private registry
      run: npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN -g
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
    - run: |
        yarn
        yarn test
      shell: bash
