name: Run Tests

inputs:
  npmToken:
    description: 'NPM Token'
    required: true

runs:
  using: "composite"
  steps:
    - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN -g
      env:
        NPM_TOKEN: ${{ inputs.npmToken }}
    - run: yarn
    - run: yarn test --passWithNoTests
