name: Big Blue Helm Action
description: Deploys a helm chart
author: Big Blue Swim School
icon: box
color: blue-dark
inputs:
  apm:
    description: Enable APM (default true)
  configs:
    description: ConfigMaps
  secrets:
    description: Secrets
  name:
    description: Name of the service
  region:
    description: Region of the deployment
  type:
    description: Service Types (express | nestjs)
  namespace:
    description: Kubernetes namespace name.
  repository:
    description: Repository
  version:
    description: Repository
  readinessPath:
    description: Path to determine when service is active
runs:
  using: docker
  image: Dockerfile