name: Big Blue Deploy Action
description: Deploys a big blue service
author: Big Blue Swim School
icon: box
color: blue-dark
inputs:
  name:
    description: Repository Name
  environment:
    description: Environment to deploy
  imageTag:
    description: Image Tag to deploy
  ghaToken:
    description: Github Actions Token
runs:
  using: docker
  image: Dockerfile