apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.port | default 3000 }}
      protocol: TCP
      targetPort: {{ .Values.port | default 3000 }}
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.type | default "NodePort" }}
