name: Build Trunk

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'package.json'

jobs:
  version:
    name: Increment Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout Repo
      - uses: bigblueswimschool/actions/version@v1
        name: Increment Pre-Release Version
        with:
          level: 'prerelease'