name: Tag Release

on:
  push:
    branches: [ release/* ]

jobs:
  version:
    if: "!contains(github.event.head_commit.message, 'Build')"
    name: Increment Patch Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout Repo
      with:
        token: ${{ secrets.PAT }}
    - uses: bigblueswimschool/actions/version@v1
      name: Increment Patch Version