name: Tag Release

on:
  push:
    branches: 
      - release/*
    paths-ignore:
      - 'package.json'

jobs:
  version:
    name: Increment Patch Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      name: Checkout Repo
      with:
        token: ${{ secrets.PAT }}
    - uses: bigblueswimschool/actions/version@develop
      name: Increment Patch Version
      with:
        alias-tags: true